[package]
name = "text-game"
version = "0.0.1"
authors = ["cod10129"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
fastrand = "1.9.0"
